name: CI
on: [push, pull_request]

jobs:
  node-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: ESLint
      run: pnpm run lint
    - name: Test suite
      run: pnpm test
    - name: Bundle
      run: pnpm run build
    - name: Test suite using bundle
      run: TEST_DIST=1 pnpm test
    - name: Load bundled code
      run: node --input-type=module -e "import('./dist/automerge.js')"
    - name: Load ES modules
      run: node --experimental-vm-modules test/esm_smoke.js

  npm-publish:
    name: npm-publish
    if: ${{ github.repository == 'automerge/automerge' && github.ref == 'refs/heads/main' }}
    needs: [ node-build ]
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: npm publish if version has been updated
      uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
